---
language: python
services: docker

env:
  global:
    - ROLE_NAME: autologin
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: fedora27
    - MOLECULE_DISTRO: fedora29
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804

install:
  - pip install molecule docker

before_script:
  - cd ..
  - mv ansible-role-$ROLE_NAME ntd.$ROLE_NAME
  - cd ntd.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
